name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest test_model.py -v --cov=.
        
    - name: Quick training test
      run: |
        python train.py
        
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: models/

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/ 